
services:
  pocketbase:
    image: spectado/pocketbase:latest
    volumes:
      - ./pocketbase_data:/pb_data
    ports:
      - "8090:8090"
    restart: always

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    depends_on:
      - pocketbase
    restart: always

  thirdweb:
    image: thirdweb/engine:v2.1.42 # always use the versioned image instead of latest, see readme for more info
    environment:
      - DATABASE_URL=http://host.docker.internal:8090
      - REDIS_URL=redis://host.docker.internal:6379
      - THIRDWEB_API_SECRET_KEY=Lwty4iJ2ebBPcS1ZmaoTaK-tDCjhHVyvJoEolfpEo6wLFYp3AF6vPPA7LsIsahPv5M3HTAlxaMNZfye1QZJ9ow # from portal
      - ADMIN_WALLET_ADDRESS=0x424f24742E9a4e668d601DE15F507478eB690Acb # from portal
      - ENGINE_URL="https://jib-3rd-node.ruk.solutions"
      - ENABLE_HTTPS="false"
      - ENCRYPTION_PASSWORD=true
      #env_file:
      #- ./.env
    ports:
      - "3005:3005"
    depends_on:
      - pocketbase
      - redis
    restart: always
